CREATE TABLE FACT_SALES (
    -- Foreign Keys 
    CAR_DIM_ID          NUMBER,
    DIST_DIM_ID         NUMBER,
    CUST_DIM_ID         NUMBER,
    TIME_DIM_ID         NUMBER,
    ORIGIN_DIM_ID       NUMBER,

    -- Numeric, Additive Measures
    UNITS_SOLD          NUMBER,
    SELL_PRICE          NUMBER,
    DISCOUNT_AMOUNT     NUMBER,

    CONSTRAINT fk_fs_car FOREIGN KEY (CAR_DIM_ID) REFERENCES DIM_CAR(CAR_DIM_ID),
    CONSTRAINT fk_fs_dist FOREIGN KEY (DIST_DIM_ID) REFERENCES DIM_DISTRIBUTOR(DIST_DIM_ID),
    CONSTRAINT fk_fs_cust FOREIGN KEY (CUST_DIM_ID) REFERENCES DIM_CUSTOMER_DATA(CUST_DIM_ID),
    CONSTRAINT fk_fs_time FOREIGN KEY (TIME_DIM_ID) REFERENCES DIM_TIME(TIME_ID),
    CONSTRAINT fk_fs_origin FOREIGN KEY (ORIGIN_DIM_ID) REFERENCES DIM_CAR_ORIGIN(ORIGIN_ID)
);


--

INSERT INTO FACT_SALES (
    CAR_DIM_ID, DIST_DIM_ID, CUST_DIM_ID, TIME_DIM_ID, ORIGIN_DIM_ID,
    UNITS_SOLD, SELL_PRICE, DISCOUNT_AMOUNT
)
WITH CUSTOMER_SALE_DATA AS (
  SELECT
    C.ID AS CUSTOMER_ID,
    C.GENDER,
    C.EDUCATIONAL_LEVEL,
    CASE
      WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, C.BIRTHDAY) / 12) < 25 THEN 'Under 25'
      WHEN TRUNC(MONTHS_BETWEEN(SYSDATE, C.BIRTHDAY) / 12) BETWEEN 25 AND 40 THEN '25-40'
      ELSE 'Over 40'
    END AS AGE_BUCKET,
    NTILE(5) OVER (ORDER BY C.ANNUAL_INCOME) AS SALARY_RANGE
  FROM CUSTOMERS_DATA C
)
SELECT
    dc.CAR_DIM_ID,
    dd.DIST_DIM_ID,
    dcu.CUST_DIM_ID,
    dt.TIME_ID,
    dco.ORIGIN_ID,

    1 AS UNITS_SOLD, 
    so.SELL_PRICE,
    (dc.RETAIL_PRICE - so.SELL_PRICE) AS DISCOUNT_AMOUNT 
FROM
    SELL_ORDERS_DATA so

JOIN DIM_CAR dc ON so.CAR_ID = dc.CAR_ID

JOIN DIM_DISTRIBUTOR dd ON so.DISTRIBUTOR_ID = dd.DISTRIBUTOR_ID

JOIN DIM_TIME dt ON dt.YEAR = EXTRACT(YEAR FROM so.SELL_DATE) AND dt.MONTH_NUMBER = EXTRACT(MONTH FROM so.SELL_DATE)

JOIN DIM_CAR_ORIGIN dco ON dc.MAKE = dco.MAKE

JOIN CUSTOMER_SALE_DATA csd ON so.CUSTOMER_ID = csd.CUSTOMER_ID
JOIN DIM_CUSTOMER_DATA dcu ON -- ver en donde es que esta el match, para poder sacar el CUST_DIM_ID
    dcu.GENDER = csd.GENDER
    AND dcu.EDUCATIONAL_LEVEL = csd.EDUCATIONAL_LEVEL
    AND dcu.AGE_BUCKET = csd.AGE_BUCKET
    AND dcu.SALARY_RANGE = csd.SALARY_RANGE;


SELECT * FROM FACT_SALES;

COMMIT;

